# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160626_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynergyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=20)),
                ('users', models.ManyToManyField(blank=True, to='users.SynergyUser')),
            ],
        ),
    ]
